//
//  VariationBRouter.swift
//  ABTesting
//
//  Created by Raymond Law on 8/22/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol VariationBRoutingLogic
{
  func routeToHome(segue: UIStoryboardSegue?)
}

protocol VariationBDataPassing
{
  var dataStore: VariationBDataStore? { get }
}

class VariationBRouter: NSObject, VariationBRoutingLogic, VariationBDataPassing
{
  weak var viewController: VariationBViewController?
  var dataStore: VariationBDataStore?
  
  // MARK: Routing
  
  func routeToHome(segue: UIStoryboardSegue?)
  {
  }
  
  // MARK: Navigation
  
  func navigateToHome(source: VariationBViewController, destination: HomeViewController)
  {
  }
  
  // MARK: Passing data
  
  func passDataToHome(source: VariationBDataStore, destination: inout HomeDataStore)
  {
  }
}
