//
//  HomeInteractor.swift
//  ABTesting
//
//  Created by Raymond Law on 8/22/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func viewProduct(request: Home.ViewProduct.Request)
  func updateBuyersCount(request: Home.UpdateBuyersCount.Request)
}

protocol HomeDataStore
{
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
  var presenter: HomePresentationLogic?
  var worker = HomeWorker()
  
  // MARK: View product
  
  func viewProduct(request: Home.ViewProduct.Request)
  {
    let response = Home.ViewProduct.Response()
    presenter?.presentProduct(response: response)
  }
  
  // MARK: Update buyers count
  
  func updateBuyersCount(request: Home.UpdateBuyersCount.Request)
  {
    let response = Home.UpdateBuyersCount.Response(variationAViews: PurchaseFlowABTest.variationAViews, variationABuys: PurchaseFlowABTest.variationABuys, variationBViews: PurchaseFlowABTest.variationBViews, variationBBuys: PurchaseFlowABTest.variationBBuys)
    presenter?.formatBuyersCount(response: response)
  }
}
