//
//  HomeModels.swift
//  ABTesting
//
//  Created by Raymond Law on 8/22/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum ViewProduct
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  
  enum UpdateBuyersCount
  {
    struct Request
    {
    }
    struct Response
    {
      var variationAViews: Int
      var variationABuys: Int
      var variationBViews: Int
      var variationBBuys: Int
    }
    struct ViewModel
    {
      var counts: String
    }
  }
}
