//
//  HomePresenter.swift
//  ABTesting
//
//  Created by Raymond Law on 8/22/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentProduct(response: Home.ViewProduct.Response)
  func formatBuyersCount(response: Home.UpdateBuyersCount.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: View product
  
  func presentProduct(response: Home.ViewProduct.Response)
  {
    let viewModel = Home.ViewProduct.ViewModel()
    viewController?.displayProduct(viewModel: viewModel)
  }
  
  // MARK: Update buyers count
  
  func formatBuyersCount(response: Home.UpdateBuyersCount.Response)
  {
    let counts = "A: \(response.variationABuys)/\(response.variationAViews)\nB: \(response.variationBBuys)/\(response.variationBViews)"
    let viewModel = Home.UpdateBuyersCount.ViewModel(counts: counts)
    viewController?.displayBuyersCount(viewModel: viewModel)
  }
}
