//
//  HomeRouter.swift
//  ABTesting
//
//  Created by Raymond Law on 8/22/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic
{
  func routeToProduct(segue: UIStoryboardSegue?)
  func routeToVariationA(segue: UIStoryboardSegue?)
  func routeToVariationB(segue: UIStoryboardSegue?)
}

protocol HomeDataPassing
{
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing
{
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
  func routeToProduct(segue: UIStoryboardSegue?)
  {
  }
  
  func routeToVariationA(segue: UIStoryboardSegue?)
  {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "VariationAViewController") as! VariationAViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToVariationA(source: dataStore!, destination: &destinationDS)
    navigateToVariationA(source: viewController!, destination: destinationVC)
  }
  
  func routeToVariationB(segue: UIStoryboardSegue?)
  {
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let destinationVC = storyboard.instantiateViewController(withIdentifier: "VariationBViewController") as! VariationBViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToVariationB(source: dataStore!, destination: &destinationDS)
    navigateToVariationB(source: viewController!, destination: destinationVC)
  }
  
  // MARK: Navigation
  
  func navigateToVariationA(source: HomeViewController, destination: VariationAViewController)
  {
    source.show(destination, sender: nil)
  }
  
  func navigateToVariationB(source: HomeViewController, destination: VariationBViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToVariationA(source: HomeDataStore, destination: inout VariationADataStore)
  {
  }
  
  func passDataToVariationB(source: HomeDataStore, destination: inout VariationBDataStore)
  {
  }
}
