//
//  VariationAPresenter.swift
//  ABTesting
//
//  Created by Raymond Law on 8/22/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol VariationAPresentationLogic
{
  func formatReceipt(response: VariationA.Buy.Response)
}

class VariationAPresenter: VariationAPresentationLogic
{
  weak var viewController: VariationADisplayLogic?
  
  // MARK: Buy
  
  func formatReceipt(response: VariationA.Buy.Response)
  {
    let viewModel = VariationA.Buy.ViewModel()
    viewController?.displayReceipt(viewModel: viewModel)
  }
}
